### ISSUE TITLE
Decide on key metadata (e.g. new form vs existing profiles)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/ecosystem#143]
We want to know what metadata fields we're adding to profiles for the time being.

## Acceptance

- [x] We have identified how to consolidate metadata **🚧2023-11-28 we have list in https://docs.google.com/spreadsheets/d/1YcIQP_CGYhpMTzEQU_f46j159UalqLVfGt2chhsoQxw/edit#gid=1239522110 and nearly done in analysis** **✅2023-11-29*we have finalized the list *
- [x] We have a plan for updating **See #150**

Bonus:

- [x] document old metadata (from 2021) in `templates/profile-v1-2021` **Pasted from Org Metadata tab in https://docs.google.com/spreadsheets/d/1sotA3Cm79B1te4ooMQvPk6OHdaxZwnDB2VRLtfQAuRE/edit#gid=106528583 into new file templates/profile-v1-2021. Pasted in directly as a table for now.**

### Analyse current situation

- [x] What is current metadata list on **✅2023-11-28 https://docs.google.com/spreadsheets/d/1YcIQP_CGYhpMTzEQU_f46j159UalqLVfGt2chhsoQxw/edit#gid=1239522110**
- [x] What is new metadata list
- [x] How can we converge?

**Comment by catherinet1** [comment]
FIXED. Analysis and agreement of metadata fields is here: https://docs.google.com/spreadsheets/d/1YcIQP_CGYhpMTzEQU_f46j159UalqLVfGt2chhsoQxw/edit#gid=1239522110. Plan of work for updating is here: #150.
