### ISSUE TITLE
Visualisation Sync meeting 2023-12-08 - including next steps

### ISSUE THREAD

**Issue by catherinet1** [life-itself/ecosystem#180]
Meeting notes from 2023-12-08 and next steps

## Next steps

- [x] #183 
- [x] #185 **Discussion thread here: https://github.com/orgs/life-itself/discussions/969**
- [ ] #184 @mattosborn 
- [x] Schedule another meeting **Scheduled for Thursday 21st 10:30am-12:30pm CET and all have RSVPed yes**
- [ ] [@rufuspollock] Ship blog post of notes re World Values Survey book (from feb 2023)
- [x] https://github.com/life-itself/ecosystem/issues/193 @catherinet1

## Meeting Notes

**🚚 PROCESSED as of 2023-12-19 to various places e.g. sensemaking etc**

Research 2023-12-08 - Sync re ecosystem mapping/visualisations

Agenda:

- Updates re ecosystem research + database
    - Meeting with Work package 4
- Overview of project
- Where were we last time? Meeting notes from last time: [life-itself/ecosystem#151](https://github.com/life-itself/ecosystem/issues/151)

Notes:

- Overview of the project: [https://lifeitself.org/blog/2023/08/30/cohere-erasmus-mapping-announce](https://lifeitself.org/blog/2023/08/30/cohere-erasmus-mapping-announce)
    - LI are leading work package 2: mapping the field and sensemaking of the map
- "Collectives" Mapping that WP4 partners started
- Map as "broad visual of the landscape of what you're focusing on, and the ability to navigate around it", e.g. [https://twitter.com/exgenesis/status/1562059107233894402/photo/1](https://twitter.com/exgenesis/status/1562059107233894402/photo/1)
    - proximity of mapped elements, e.g. ideas or projects or goals
- Excalidraw: [https://link.excalidraw.com/l/9u8crB2ZmUo/9aEPCn1DhfJ](https://link.excalidraw.com/l/9u8crB2ZmUo/9aEPCn1DhfJ)
    - Previous Cohere+ visualisations brainstorm: [https://app.excalidraw.com/l/9u8crB2ZmUo/At9xepR5sQS](https://app.excalidraw.com/l/9u8crB2ZmUo/At9xepR5sQS)
- Questions:
    - How do we identify "centres" of the field/"tribes"?
        - Data-driven or gut instinct or ask people in some way (or combination)
    - What is a "community" (as centre)? Group of people that gather in some way whether in person or online, and united by some shared values and interests
- The centres are there as scaffolding to support sensemaking of what we're mapping
- Matt: what gives me a quick sense of an org is what are they trying to do and how are they doing it?
- What is our overall goal/priority objective with the map?
    - Is it mostly about sensemaking or catalysing connections in the field? (These seem like different goals) *_Sensemaking is priority 🔥_

What's next?

- What are some different directions or paths we could go down? (What are the nodes in the map?): create a shortlist of potential options. (Generate list of all possible nodes)
    - One path might be refining our brainstorm, i.e. nodes are thinkers/hubs/communities (mostly about ideas - thinkers, idea hubs etc.)
    - Nodes are projects
- Identify a few nodal/network "experts" and record conversations where people draw out their own map of the space/identify communities?
    - e.g. Richard Bartlett, Elizabeth Debold/Thomas Steininger (closer to Integral), someone from Plum Village (Zen Buddhism)

**Comment by catherinet1** [comment]
@mattosborn are you happy to take the lead on drafting a blog post or discussion thread  on this piece, and let me know if you want my input in some way? 

- [ ] Blog post or discussion thread re tribes/centres brainstorm (and related efforts)
  - [ ] [@mattosborn] draft a short discussion thread on forum about inspiration for visualization in related areas
  - [ ] [Both] existing tribes / research

**Comment by catherinet1** [comment]
Hi @mattosborn and @rufuspollock, checking in on our next actions from last meeting as we are meeting again this Thursday -- how is it going?

I will start working directly on this issue today: https://github.com/life-itself/ecosystem/issues/185.

P.S. I consolidated some of our meeting notes and e.g. Excalidraw brainstorms at ecosystem.lifeitself.org/sensemaking so that we have one page we can refer back to and continue to build on.

**Comment by mattosborn** [comment]
> Hi @mattosborn and @rufuspollock, checking in on our next actions from last meeting as we are meeting again this Thursday -- how is it going?

I've not had a chance to look at this yet unfortunately. My laptop died just before I sat down for work on Monday morning and I've only just received it back from the repair shop, so it's not been a very productive week for me so far. I'll try to put a quick forum post up with some notes before our meeting tomorrow
