### ISSUE TITLE
Circular Packing Visualization

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/ecosystem#50]
When looking at organizations i want to see them quickly grouped e.g. by primary topic so that I get a sense of clusters

Note: this could work even better if topics were themselves hierarchically organized as we would get 2 levels ...

Example:

* https://observablehq.com/@analyzer2004/plot-gallery
* https://observablehq.com/@d3/zoomable-circle-packing - zoomable and less labels

<img src="https://i.imgur.com/DxPUGbm.png" height="450" />

## Acceptance

* [x] A circular packing map like the above example using the topic classification and each smallest circle is an org - probably follow https://observablehq.com/@d3/zoomable-circle-packing but with outer "everything" item as a circle rather than box as in https://observablehq.com/@analyzer2004/plot-gallery
  
  * [x] have one big circle like the plot	
  * [x] only use the primary topic (to start with)
  * [x] zooming

  *Using only logos for now based on screenshot reviews in comments*
  * [x] ~~labels on the orgs~~
  * [x] ~~show clear labels if possibles on both the primary circles and the subcircles (take screenshot and we can discuss if messy)~~

* [x] Circular vis on page [/vis2](https://ecosystem.lifeitself.us/vis2) **This page was deleted? It is no longer found.**
* [x] Add to frontpage with caption/blurb from https://docs.google.com/document/d/1VIYhUF1Ti8PGqXIuqs-l4G28_1ewxfKuNcdmUwNWPUk/edit# **Frontpage links to .../vis where there is a TOC listing the ternary and circle vis, but links to the headings for each vis are not working**

Bonus

* [x] Use logos instead of labels on the circles for organizations

*Skipping the following for now*
* [ ] try two levels using the secondary topic
* [ ] (BONUS) do by activity too

## Next Actions

* [x] Add blurb from https://docs.google.com/document/d/1VIYhUF1Ti8PGqXIuqs-l4G28_1ewxfKuNcdmUwNWPUk/edit# to https://ecosystem.lifeitself.us/vis
* [x] Embed circular vis on https://ecosystem.lifeitself.us/vis
* [ ] Link from frontpage to https://ecosystem.lifeitself.us/vis to heading for circular packing vis 

_Skipping the following for now_

Can reuse code from work in #47 and even do in the same page for now.

* [ ] pull images direct from URL if there is no cached version
* [ ] add labels to the big circles on circular vis - text following the circle, in a font and colour which is easy to read
* [ ] try a different colour palette for slightly more contrast between main circle and topic circles (considering not priority)

**Comment by rufuspollock** [comment]
@khalilcodes can we close this? Can you update acceptance criteria if front page work is done.

**Comment by catherinet1** [comment]
I added the blurb for this vis and embedded the vis on https://ecosystem.lifeitself.us/vis.

I wanted to link from frontpage where the circular vis is to the heading #Visualizing the Ecosystem by Topic on https://ecosystem.lifeitself.us/vis. However, the URL https://ecosystem.lifeitself.us/vis#Visualizing-the-Ecosystem-by-Topic didn't work and I didn't know why.

So I created a heading and TOC to introduce the visualisations page and allow people to navigate from the top to either vis (so people are not confused when they click the link to explore the circular vis and are taken to a page where they see only the ternary vis at the top, and may not know immediately to scroll down to find the circular vis). However, the links to either heading in the TOC are not working and I can't figure out why right now. 

@khalilcodes would you be able to help with this? I imagine it's likely there's something quick and simple I'm missing. It would be great if the link from circular vis on frontpage could go directly to the heading #Visualizing the Ecosystem by Topic on https://ecosystem.lifeitself.us/vis

**Comment by rufuspollock** [comment]
@catherinet1 the issue with linking to anchors is a known bug in flowershow that we are fixing. That's easy to do.

**Comment by rufuspollock** [comment]
FIXED.
