### ISSUE TITLE
[ux] allow people to return to the same spot on the profile list having viewed individual profile

### ISSUE THREAD

**Issue by theo-cox** [life-itself/ecosystem#52]
When using the ecosystem.lifeitself.us I want the UX to be as functional and intuitive as possible so it is easy for me to use and derive value from it as a tool.

Further background is Nathen has been using the site, and offered the following feedback: 

_When you open up an individual project and then press the back button it takes you back to the top of the home page. It might be better to either open each project in a new window, or make each project a pop-up, or anchor to the point on the page when you press back._

## Acceptance

- [ ] Implemented method of allowing people to return to the same spot on the profile list having reviewed an individual profile

**Comment by rufuspollock** [comment]
WONTFIX. not that important IMO, at least for now.
